### ISSUE TITLE
Android 10

### ISSUE THREAD

**Issue by Akash84016** [tcking/GiraffeCompressor#18]
android 10 not support video converting error below like show

Fatal Exception: android.media.MediaCodec$CodecException: Error 0xfffffff3
       at android.media.MediaCodec.native_queueInputBuffer(MediaCodec.java)
       at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2450)
       at com.github.tcking.giraffecompressor.mediacodec.LollipopMediaCodecVideoCompressor$2.onInputBufferAvailable(LollipopMediaCodecVideoCompressor.java:115)
       at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
       at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by wadejohnson650** [comment]
@akash84016 I'm facing the same issue , have you found anything to fix this issue ?

**Comment by Suyash171** [comment]
Same for me
