### ISSUE TITLE
Error When use Library

### ISSUE THREAD

**Issue by masoudzeeb** [tcking/GiraffeCompressor#23]
2020-10-14 16:49:55.114 15418-15595/in.zeeb.messenger I/MediaCodec: setCodecState state : 1
2020-10-14 16:49:55.114 15418-15596/in.zeeb.messenger W/MapperHal: buffer descriptor with invalid usage bits 0x200000
2020-10-14 16:49:55.117 15418-15596/in.zeeb.messenger W/MapperHal: buffer descriptor with invalid usage bits 0x200000
2020-10-14 16:49:55.123 15418-15583/in.zeeb.messenger D/ACodec: dataspace changed to 0x10c10000 (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) (R:2(Limited), S:1(BT709), T:3(SMPTE_170M))
2020-10-14 16:49:55.124 15418-15596/in.zeeb.messenger W/MapperHal: buffer descriptor with invalid usage bits 0x200000
2020-10-14 16:49:55.126 15418-15596/in.zeeb.messenger W/MapperHal: buffer descriptor with invalid usage bits 0x200000
2020-10-14 16:49:55.150 15418-15582/in.zeeb.messenger I/MediaCodec: setCodecState state : 1
2020-10-14 16:49:55.151 15418-15609/in.zeeb.messenger I/MPEG4Writer: setStartTimestampUs: 0 from Video track
2020-10-14 16:49:55.151 15418-15609/in.zeeb.messenger I/MPEG4Writer: Earliest track starting time: 0
2020-10-14 16:49:55.908 15418-15594/in.zeeb.messenger ****E/AndroidRuntime: FATAL EXCEPTION: decoder-thread
    Process: in.zeeb.messenger, PID: 15418
    android.media.MediaCodec$CodecException: Error 0xfffffff3
        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2450)
        at com.github.tcking.giraffecompressor.mediacodec.LollipopMediaCodecVideoCompressor$2.onInputBufferAvailable(LollipopMediaCodecVideoCompressor.java:115)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)****

**Comment by masoudzeeb** [comment]
Please Help ME

**Comment by Vijay0710** [comment]
Did you find any solution for this?
