### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Surface frame wait timed out

### ISSUE THREAD

**Issue by shashwatwebappmate** [tcking/GiraffeCompressor#8]
Fatal Exception: java.lang.RuntimeException: Surface frame wait timed out
       at com.github.tcking.giraffecompressor.mediacodec.OutputSurface.awaitNewImage(Unknown Source)
       at com.github.tcking.giraffecompressor.mediacodec.LollipopMediaCodecVideoCompressor$2.onOutputBufferAvailable(Unknown Source)
       at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1558)
       at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1505)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by geet000** [comment]
I have same issue
